import "@/styles/global.css";
import { NprogressProvider } from "@/context/NprogressContext";
import Head from "next/head";

export default function App({ Component, pageProps }) {
    return (
        <NprogressProvider>
            <Head>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <title>NaNaNames - Generate pet names using AI</title>
            </Head>
            <Component {...pageProps} />
        </NprogressProvider>
    );
}
